language: python
sudo: false
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
install:
    - make build
script:
    - make test
notifications:
    irc:
        channels: 
            - "irc.mozilla.org#services-dev"
        on_success: change
